In [ ]:
# Based on code from the following link:
# https://towardsdatascience.com/multi-label-classification-using-bert-roberta-xlnet-xlm-and-distilbert-with-simple-transformers-b3e0cda12ce5

In [ ]:
#!pip install simpletransformers==0.34.4

In [ ]:
# import keras
# keras.__version__

In [ ]:
# import tensorflow
# tensorflow.__version__

In [ ]:
# import torch
# torch.__version__

In [ ]:
# !jupyter --version

In [ ]:
# !pip install scikit-learn==0.23.1

In [ ]:
# !pip install pandas==1.0.5

In [ ]:
# !pip show simpletransformers 

In [ ]:
# import sklearn
# sklearn.__version__

In [1]:
import pandas as pd
#from simpletransformers.classification import MultiLabelClassificationModel
import ast

In [2]:
from simpletransformers.experimental.classification import MultiLabelClassificationModel

# Model Training

In [3]:
df = pd.read_csv('./train.tsv', sep='\t')

In [ ]:
df.labels = df.labels.apply(eval)

In [ ]:
model = MultiLabelClassificationModel('bert', "emilyalsentzer/Bio_ClinicalBERT", num_labels=124, 
                                      args={'train_batch_size':4,
                                            'gradient_accumulation_steps':16,
                                            'learning_rate': 3e-5,
                                            'num_train_epochs': 3,
                                            'max_seq_length': 512,
                                            'reprocess_input_data': True,
                                            'overwrite_output_dir': True})

In [ ]:
model.train_model(df)

# Sliding Window Experimental Model Training

In [1]:
import pandas as pd
#from simpletransformers.classification import MultiLabelClassificationModel
import ast
from simpletransformers.experimental.classification import MultiLabelClassificationModel

df = pd.read_csv('./train.tsv', sep='\t')
df.labels = df.labels.apply(eval)

In [2]:
model = MultiLabelClassificationModel('bert', "emilyalsentzer/Bio_ClinicalBERT", num_labels=124, 
                                      args={'train_batch_size':4,
                                            'sliding_window': True,
                                            'stride': 0.8,
                                            'gradient_accumulation_steps':16,
                                            'learning_rate': 3e-5,
                                            'num_train_epochs': 3,
                                            'max_seq_length': 512,
                                            'reprocess_input_data': True,
                                            'overwrite_output_dir': True,
                                            'no_cache': True,
                                            'multiprocessing_chunksize': 410,
                                           'tensorboard_dir':'./outputs/',
                                           'wandb_project': False,
                                           'save_model_every_epoch': True,
                                           'no_save': False,
                                           'save_optimizer_and_scheduler': True})

In [3]:
model.train_model(df)

Running loss: 0.724157

C:\Users\brent\anaconda3\lib\site-packages\torch\optim\lr_scheduler.py:231: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


Running loss: -0.383459

C:\Users\brent\anaconda3\lib\site-packages\torch\optim\lr_scheduler.py:200: UserWarning: Please also save or load the state of the optimzer when saving or loading the scheduler.
  warnings.warn(SAVE_STATE_WARNING, UserWarning)


Running loss: -48.270176


Running loss: -68.9806068


Running loss: -57.6811602



# Model Evaluation

In [1]:
import pandas as pd
#from simpletransformers.classification import MultiLabelClassificationModel
import ast
from simpletransformers.experimental.classification import MultiLabelClassificationModel
import sklearn

In [3]:
model = MultiLabelClassificationModel('bert', "./outputs/checkpoint-95931-epoch-3", num_labels=124,
                                      args={'train_batch_size':4,
                                            'sliding_window': True,
                                            'stride': 0.8,
                                            'gradient_accumulation_steps':16,
                                            'learning_rate': 3e-5,
                                            'num_train_epochs': 3,
                                            'max_seq_length': 512,
                                            'reprocess_input_data': True,
                                            'overwrite_output_dir': True,
                                            'no_cache': True,
                                            'multiprocessing_chunksize': 410,
                                           'tensorboard_dir':'./outputs/',
                                           'wandb_project': False,
                                           'save_model_every_epoch': True,
                                           'no_save': False,
                                           'save_optimizer_and_scheduler': True})

In [4]:
eval_df = pd.read_csv('./test.tsv', sep='\t')
eval_df.labels = eval_df.labels.apply(eval)

In [5]:
predictions, raw_outputs = model.predict(eval_df['text'])

In [151]:
temp[temp>cut_off] = 1

In [153]:
temp[temp<=cut_off] = 0

NameError: name 'cut_off' is not defined

In [152]:
temp

array([1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.93725273e-01, 1.00000000e+00,
       1.00000000e+00, 4.63010430e-01, 4.52351540e-01, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 2.64921645e-03,
       2.45726556e-01, 2.48698726e-01, 3.63780782e-02, 6.20990977e-05,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 6.26747459e-02,
       1.36235490e-01, 2.28680093e-02, 1.12093553e-01, 1.85693994e-01,
       5.31695001e-02, 8.80044475e-02, 1.77689031e-01, 4.84473296e-02,
       1.02262601e-01, 9.28874686e-02, 1.35574982e-01, 1.39520885e-02,
       2.93414760e-02, 3.72750387e-02, 5.90621941e-02, 3.95298190e-02,
       3.54282185e-02, 1.15129501e-01, 4.02598232e-02, 1.35952204e-01,
       9.99243855e-02, 5.29490672e-02, 3.52977812e-02, 6.60769939e-02,
       7.09423274e-02, 6.69625774e-02, 3.64643894e-02, 3.63761872e-01,
       9.08318013e-02, 6.29929677e-02, 7.75776729e-02, 1.78049151e-02,
      

In [154]:
y_pred = np.empty((0,124))
cut_off = 0.5
for i in range(len(raw_outputs)):
    temp = np.max(raw_outputs[i], axis=0)
    temp[temp>cut_off] = 1
    temp[temp<=cut_off] = 0
    y_pred = np.vstack([y_pred,temp])

In [176]:
y_true = np.array(eval_df['labels'].tolist())
y_true[y_true > 1] = 1

In [177]:
y_true.shape

(2882, 124)

In [178]:
y_pred.shape

(2882, 124)

In [179]:
y_pred

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.]])

In [180]:
y_true

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [183]:
print(sklearn.metrics.f1_score(y_true, y_pred, average=None))

[0.90419806 0.83954097 0.81695389 0.65557316 0.60609388 0.42431762
 0.         0.75722294 0.54137931 0.         0.         0.84465825
 0.60435835 0.57574909 0.59107291 0.         0.         0.
 0.         0.6593674  0.5382193  0.60609388 0.83954097 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.22258065 0.36255572
 0.         0.         0.       

In [185]:
print(sklearn.metrics.f1_score(y_true, y_pred, average='macro'))

print(sklearn.metrics.f1_score(y_true, y_pred, average='micro'))

print(sklearn.metrics.f1_score(y_true, y_pred, average='weighted'))

print(sklearn.metrics.f1_score(y_true, y_pred, average='samples', zero_division=1))

print(sklearn.metrics.f1_score(y_true, y_pred, average=None))

0.11021101808152838
0.5653615855660068
0.4346269070578652
0.5554657191041477
[0.90419806 0.83954097 0.81695389 0.65557316 0.60609388 0.42431762
 0.         0.75722294 0.54137931 0.         0.         0.84465825
 0.60435835 0.57574909 0.59107291 0.         0.         0.
 0.         0.6593674  0.5382193  0.60609388 0.83954097 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.        